{% set name = "you-get" %}
{% set version = "0.4.1730" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 65457b7b8893f08c082532eb34998dc477f533d32568be3bb34e592bdcb44f88

build:
  number: 1
  noarch: python
  entry_points:
    - you-get = you_get.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - dukpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - you_get
    - you_get.cli_wrapper
    - you_get.cli_wrapper.downloader
    - you_get.cli_wrapper.openssl
    - you_get.cli_wrapper.player
    - you_get.cli_wrapper.transcoder
    - you_get.extractors
    - you_get.processor
    - you_get.util
  commands:
    - you-get --help

about:
  home: https://you-get.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Dumb downloader that scrapes the web
  description: |
    Command line downloader for YouTube and many other online video/
    audio sources.
  doc_url: https://you-get.org/
  dev_url: https://github.com/soimort/you-get

extra:
  recipe-maintainers:
    - mwcraig
