{% set name = "you-get" %}
{% set version = "0.4.1700" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cd21492012a446ac1b52c6f7e44944aac65b59e997645a84dcf64cf8043e99c

build:
  number: 0
  noarch: python
  entry_points:
    - you-get = you_get.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python >=3.2

test:
  imports:
    - you_get
    - you_get.cli_wrapper
    - you_get.cli_wrapper.downloader
    - you_get.cli_wrapper.openssl
    - you_get.cli_wrapper.player
    - you_get.cli_wrapper.transcoder
    - you_get.extractors
    - you_get.processor
    - you_get.util
  commands:
    - you-get --help

about:
  home: https://you-get.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Dumb downloader that scrapes the web
  description: |
    Command line downloader for YouTube and many other online video/
    audio sources.
  doc_url: https://you-get.org/
  dev_url: https://github.com/soimort/you-get

extra:
  recipe-maintainers:
    - mwcraig
